version: "3"

services:
  # api:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   links:
  #     - db
  #     - redis

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - 6379:6379

  db:
    image: "mongo:latest"
    hostname: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    volumes:
      - cornalitodb:/data/db
    ports:
      - 27017:27017
volumes:
  cornalitodb: {}